import { createApp } from 'vue'
import App from './App.vue'
import '@fontsource/dm-sans/latin-400.css'
import '@fontsource/dm-sans/latin-500.css'
import '@fontsource/dm-sans/latin-600.css'
import '@fontsource/manrope/cyrillic-500.css'
import '@fontsource/manrope/latin-500.css'
import './assets/main.css'
import './assets/parallax.css'
import './assets/expertise-accordion.css'
createApp(App).mount('#app')
